
general:
  project_name: 'tokenization'
  run_name: '_time:' # default run name is timestamp
  run_description: null
  out_dir: '$OUT_DIR/$project_name/$run_name'

_env: # creates env vars
  project_name: '_copy: /general/project_name'
  run_name: '_copy: /general/run_name'

logging:
  project_name: '_copy: /general/project_name'
  run_name: '_copy: /general/run_name'
  log_dir: '_copy: /general/out_dir'
  run_description: '_copy: /general/run_description'
  enable_wandb: false
  summaries_stdout: true
  log_filename: 'log.txt'
  summaries_filename: 'summaries.txt'
  allow_overwrite_log: true
  metrics_type: null

data:
  # dataset settings
  hf_name_path: null # dataset path, '$DATA_ROOT/datasets/tinystories_v2/'
  hf_dataset_name: null
  hf_data_dir: null
  hf_data_files: null
  hf_sample_by: null
  hf_revision: null
  hf_cache_dir: null
  text_column: 'text'

  # splits to tokenize
  train_split: null # auto detect 'train'
  val_split: null # set to '' to ignore existing val split and create a new one
  test_split: null # auto detect 'train'
  val_fraction: null
  test_fraction: null

  data_loader_seed: 8

  tokenized_out_dir: null # specified by the override config